name: COP
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::bedtools
  - bioconda::ucsc-bedclip
  - bioconda::ucsc-twobittofa
  - bioconda::seqkit
  - bioconda::meme
  - python=3.10
  - pip
  - pip:
    - scikit-learn
    - xgboost
    - lightgbm
    - jsonargparse
    - opt_einsum
    - einops
    - optuna
    - optuna-dashboard
    - tensorboard
    - transformers
    - diffusers
    - evaluate
    - gradio
    - tbparse
    - HolisticTraceAnalysis
    - plotnine
    - shap
    - bioframe
    - py2bit
    - setuptools==81.0.0
    - common_ai
